# Generated by Django 3.0.4 on 2020-06-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_administrative",),
        migrations.AlterField(
            model_name="user",
            name="is_academic",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the employee is academic.",
                verbose_name="employee status",
            ),
        ),
    ]
