# Generated by Django 3.0.4 on 2020-05-12 20:39

from django.db import migrations, models
import jsonfield.fields
import src.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200326_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_fee',
            field=models.PositiveIntegerField(default=0, help_text='admission\xa0fee'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='boarding_fee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='student\xa0boarding\xa0fee'),
        ),
        migrations.AddField(
            model_name='student',
            name='examiner_name',
            field=models.CharField(blank=True, help_text='Name\xa0for\xa0examiner(student)', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, help_text='Father\xa0name\xa0of\xa0student', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_information',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=src.user.models.upload_path),
        ),
        migrations.AddField(
            model_name='student',
            name='monthly_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='student\xa0monthly\xa0fee'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='Name\xa0for\xa0Registration(student)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='other_fees',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='other_information',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='present_address',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='result',
            field=models.CharField(blank=True, help_text='examiner_result', max_length=50, null=True),
        ),
    ]
