# Generated by Django 3.0.4 on 2020-04-21 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200326_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRecruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(help_text='Teacher Full name, name with title should be unique, used at time time of student assigning', max_length=60, unique=True)),
                ('teacherDistrict', models.CharField(max_length=50)),
                ('teacherUpozilla', models.CharField(max_length=70)),
                ('teacherMobileNo', models.CharField(max_length=20)),
                ('teacherVillage', models.CharField(blank=True, help_text='100 character , road no, vaillage name and housing no', max_length=100)),
                ('temporaryStartingDate', models.DateTimeField(auto_now_add=True)),
                ('recruitingSalary', models.IntegerField(help_text='Salary in BDT , at the time of recruiting')),
                ('salaryIncrementRate', models.PositiveIntegerField()),
                ('salaryIncrementDate', models.DateTimeField()),
                ('parmanentStartingDate', models.DateTimeField()),
                ('additionalResponsibilityHonor', models.CharField(blank=True, help_text='additional work beside his/her owned work', max_length=300)),
                ('resigningDate', models.DateTimeField()),
                ('commnetAboutTeacher', models.TextField(blank=True, help_text='Comment about the teacher from admin side, max 200 char', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistrationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name for Registration(student)', models.CharField(max_length=50)),
                ('student_district', models.CharField(max_length=20)),
                ('student_thana', models.CharField(max_length=20)),
                ('student_village', models.CharField(max_length=50)),
                ('student_optional_address', models.TextField(help_text='can be included post, word, house no', max_length=200)),
                ('Birth_date', models.DateField()),
                ('gaurdian_type', models.PositiveIntegerField(default=1)),
                ('can be father or relative', models.CharField(max_length=50)),
                ('gaurdian_district', models.CharField(blank=True, max_length=20)),
                ('gaurdian_thana', models.CharField(blank=True, max_length=20)),
                ('gaurdian_village', models.CharField(blank=True, max_length=50)),
                ('gaudian_occupation', models.CharField(blank=True, max_length=40)),
                ('gaurdian_mobile', models.CharField(max_length=14)),
                ('gaurdian_optional_address', models.TextField(help_text='can be included post, word, house no', max_length=200)),
                ('guardian_relationship', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssignmentToTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.PositiveIntegerField(verbose_name='student unique id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='at the time of assigning to another teacher')),
                ('teacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.TeacherRecruitment')),
            ],
        ),
    ]
