# Generated by Django 3.0.4 on 2020-05-15 09:15

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_auto_20200515_0900"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="other_information",
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
