# Generated by Django 3.0.4 on 2020-05-15 09:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_auto_20200515_0915"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="student",
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.RemoveField(model_name="student", name="id",),
        migrations.RemoveField(model_name="student", name="user",),
        migrations.AddField(
            model_name="student",
            name="user_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
