# Generated by Django 3.0.4 on 2020-05-17 10:55

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_auto_20200515_0956"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="present_address",
            field=jsonfield.fields.JSONCharField(blank=True, max_length=500, null=True),
        ),
    ]
