version: '3.7'

services:
  db:
    image: postgres:12.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: ops/dev/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - conf/.env.docker.dev
    depends_on:
      - db

volumes:
  postgres_data:
