# Generated by Django 3.0.4 on 2020-03-26 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        ("user", "0002_auto_20200326_2337"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("code", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "balance_type",
                    models.SmallIntegerField(choices=[(1, "Debit"), (-1, "Credit")]),
                ),
                (
                    "account_type",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Balance Sheet"),
                            (1, "Income Statement"),
                            (2, "Retained Earnings"),
                        ]
                    ),
                ),
                ("editable", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AccountGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.PositiveIntegerField(default=0, unique=True)),
                ("name", models.CharField(max_length=32)),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Current Assets"),
                            (1, "Non-current Assets"),
                            (2, "Current Liabilities"),
                            (3, "Non-current Liabilities"),
                            (4, "Equity"),
                            (5, "Revenue"),
                            (6, "Other Operating Income"),
                            (7, "Non-operating Income"),
                            (8, "Cost of Sales"),
                            (9, "Indirect Overhead"),
                            (10, "Non-operating Expenses"),
                            (11, "Income Taxes"),
                            (12, "Gain/Losses"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("posted_date", models.DateField(blank=True, null=True)),
                ("number", models.PositiveIntegerField(default=0)),
                ("description", models.CharField(blank=True, max_length=52, null=True)),
                ("approved", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_posted", models.BooleanField(default=False)),
                ("due_date", models.DateField(null=True)),
                (
                    "document_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Invoice"),
                            (1, "Billing"),
                            (2, "Credit Note"),
                            (3, "Debit Note"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.Organization",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="user.Student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="user.Teacher",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("posted_date", models.DateField(blank=True, null=True)),
                ("number", models.PositiveIntegerField(default=0)),
                ("description", models.CharField(blank=True, max_length=52, null=True)),
                ("approved", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_posted", models.BooleanField(default=False)),
                ("document_date", models.DateField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.Invoice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.Organization",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "last_updated",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[(1, "Debit"), (-1, "Credit")], default=1
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
                ("detail", models.CharField(blank=True, max_length=50)),
                ("extra_ref", models.CharField(blank=True, max_length=20, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounting.Account",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounting.Journal",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.Organization",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("posted_date", models.DateField(blank=True, null=True)),
                ("number", models.PositiveIntegerField(default=0)),
                ("description", models.CharField(blank=True, max_length=52, null=True)),
                ("approved", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_posted", models.BooleanField(default=False)),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Collection"), (1, "Payment")], default=0
                    ),
                ),
                (
                    "mode",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Cash"),
                            (1, "bKash"),
                            (2, "CreditCard"),
                            (3, "Cheque"),
                        ],
                        default=0,
                    ),
                ),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=11)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="accounting.Invoice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.Organization",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.Student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="user.Teacher",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="journal",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting.Payment",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting.AccountGroup",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.Organization",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account", unique_together={("organization", "code")},
        ),
    ]
