# Generated by Django 3.0.4 on 2020-05-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="gl_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="account", unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["organization", "name"], name="accounting__organiz_b811da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "posted_date"],
                name="accounting__organiz_669558_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["invoice"], name="accounting__invoice_37a9fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["payment"], name="accounting__payment_3787d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["organization", "posted_date"],
                name="accounting__organiz_adf4f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["organization", "account"],
                name="accounting__organiz_17c8a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["journal"], name="accounting__journal_b9f668_idx"
            ),
        ),
        migrations.RemoveField(model_name="account", name="code",),
    ]
