# Generated by Django 3.0.4 on 2020-06-12 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0002_auto_20200612_1341"),
        ("accounting", "0001_initial"),
        ("student", "0002_auto_20200612_1341"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="employee.Employee",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="accounting.Invoice",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.Organization",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.Student",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting.Invoice",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.Organization",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting.Payment",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="employee.Employee",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.Organization",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="student.Student",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting.AccountGroup",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.Organization",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["organization", "account"],
                name="accounting__organiz_17c8a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["journal"], name="accounting__journal_b9f668_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["organization", "posted_date"],
                name="accounting__organiz_adf4f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["invoice"], name="accounting__invoice_37a9fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["payment"], name="accounting__payment_3787d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "posted_date"],
                name="accounting__organiz_669558_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["organization", "name"], name="accounting__organiz_b811da_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account", unique_together={("organization", "name")},
        ),
    ]
