# Generated by Django 3.0.4 on 2020-06-05 16:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 5, 16, 48, 20, 501466))),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Section name', max_length=150)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 5, 16, 48, 20, 502088))),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.OrganizationClass')),
            ],
        ),
    ]
