# Generated by Django 3.0.4 on 2020-03-26 23:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("registration_no", models.CharField(max_length=10)),
                ("tin", models.CharField(max_length=12, verbose_name="TIN")),
                ("vat_reg_no", models.CharField(max_length=15)),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. 9 to 15 digits allowed.",
                                regex="^\\+?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/organizations"
                    ),
                ),
                ("tax_submission_time", models.DateField(blank=True, null=True)),
                ("trade_license_renew_time", models.DateField(blank=True, null=True)),
                (
                    "trade_license_copy",
                    models.FileField(blank=True, null=True, upload_to="scanned_copies"),
                ),
                (
                    "tin_copy",
                    models.FileField(blank=True, null=True, upload_to="scanned_copies"),
                ),
                (
                    "vat_copy",
                    models.FileField(blank=True, null=True, upload_to="scanned_copies"),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice", models.PositiveIntegerField(default=0)),
                ("billing", models.PositiveIntegerField(default=0)),
                ("payment", models.PositiveIntegerField(default=0)),
                ("collection", models.PositiveIntegerField(default=0)),
                ("credit_note", models.PositiveIntegerField(default=0)),
                ("debit_note", models.PositiveIntegerField(default=0)),
                ("journal", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.Organization",
                    ),
                ),
            ],
        ),
    ]
