# Generated by Django 3.0.4 on 2020-06-13 09:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_auto_20200612_1639"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee", old_name="amount", new_name="gross_salary",
        ),
        migrations.RenameField(
            model_name="employee", old_name="image", new_name="photo",
        ),
        migrations.RemoveField(model_name="legalinformation", name="additional_field",),
        migrations.AddField(
            model_name="legalinformation",
            name="additional_info",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="legalinformation",
            name="education_background",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="legalinformation",
            name="permanent_address",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="legalinformation",
            name="present_address",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
