# Generated by Django 3.0.4 on 2020-06-05 17:02

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_app', '0002_auto_20200605_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('gender', models.CharField(max_length=50, verbose_name='gender of student')),
                ('roll_no', models.CharField(max_length=150, verbose_name='serial or roll ')),
                ('address', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 5, 17, 2, 28, 384348))),
                ('admitted_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='class_app.OrganizationClass')),
                ('admitted_section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='class_app.Section')),
            ],
        ),
        migrations.CreateModel(
            name='GuardianInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('relationship', models.CharField(max_length=50, verbose_name='relation with student')),
                ('gender', models.CharField(max_length=50, verbose_name='gender of guardian')),
                ('mobile', models.CharField(max_length=20, verbose_name='mobil no ')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('present_address', django.contrib.postgres.fields.jsonb.JSONField()),
                ('permanent_address', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 5, 17, 2, 28, 385298))),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitted_fees', models.PositiveIntegerField(verbose_name='at the of admitted to organization')),
                ('monthly_fees', models.PositiveIntegerField(default=0, verbose_name='payable for every month')),
                ('additional_fees', django.contrib.postgres.fields.jsonb.JSONField()),
                ('payment', models.PositiveIntegerField(verbose_name='amount of payment')),
                ('payment_date', models.DateField(verbose_name='date of payment')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
