# Generated by Django 3.0.4 on 2020-06-06 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_auto_20200606_1057"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "fee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.StudentFee",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.Student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="fees",
            field=models.ManyToManyField(
                through="student.FinancialInfo", to="accounting.StudentFee"
            ),
        ),
        migrations.AddIndex(
            model_name="financialinfo",
            index=models.Index(
                fields=["student"], name="student_fin_student_d84c30_idx"
            ),
        ),
    ]
