# Generated by Django 3.0.4 on 2020-06-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_auto_20200606_1110"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="financialinfo", name="student_fin_student_d84c30_idx",
        ),
        migrations.AddIndex(
            model_name="financialinfo",
            index=models.Index(
                fields=["student", "fee"], name="student_fin_student_13cd23_idx"
            ),
        ),
    ]
