# Generated by Django 3.0.4 on 2020-09-26 14:43

from django.db import migrations, models
import src.student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200710_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=src.student.models.upload_path_student),
        ),
    ]
