# Generated by Django 3.0.4 on 2020-06-05 16:48

import datetime
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=150, verbose_name='email address')),
                ('designation', models.CharField(blank=True, max_length=150, verbose_name="teacher's designation")),
                ('joining', models.DateField(verbose_name='date of joining')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAssigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.OrganizationClass')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.Section')),
                ('tid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_salary', models.PositiveIntegerField(default=0, verbose_name='probational period salary')),
                ('temp_joining_date', models.DateField(verbose_name='first joining date')),
                ('permanent_salary', models.PositiveIntegerField(verbose_name='permanent employee salary')),
                ('perm_joining_date', models.DateField(verbose_name='permanent joining date')),
                ('extra_responsibility', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('increment', django.contrib.postgres.fields.jsonb.JSONField()),
                ('increment_history', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type_name', models.CharField(help_text='sick, marital, others', max_length=150)),
                ('days', models.PositiveIntegerField(verbose_name='number of days leave')),
                ('starting_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 5, 16, 48, 20, 504435))),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=True)),
                ('tid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
    ]
