# Generated by Django 3.0.4 on 2020-06-06 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("user", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.Organization",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Probation"),
                            (1, "Full-Time"),
                            (3, "Part-time"),
                            (4, "Contractual"),
                        ],
                        default=1,
                    ),
                ),
                ("joining_date", models.DateField(auto_now=True)),
                ("permanent_joining_date", models.DateField(blank=True, null=True)),
                (
                    "designation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="teacher.Designation",
                    ),
                ),
                ("sections", models.ManyToManyField(blank=True, to="course.Section")),
            ],
            bases=("user.user",),
            managers=[("objects", src.user.models.UserManager()),],
        ),
        migrations.CreateModel(
            name="SalaryInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Probation Period Salary"),
                            (1, "Permanent Salary"),
                            (2, "Festival Bonus"),
                            (3, "Salary Increment"),
                        ],
                        default=1,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.Teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Casual"), (1, "Sick"), (2, "Others")], default=0
                    ),
                ),
                (
                    "days",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="number of days leave"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.Teacher",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["designation"], name="teacher_tea_designa_d658ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salaryinfo",
            index=models.Index(
                fields=["teacher"], name="teacher_sal_teacher_28fa1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leave",
            index=models.Index(
                fields=["teacher"], name="teacher_lea_teacher_e73427_idx"
            ),
        ),
    ]
